# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopose < Formula
  desc ""
  homepage ""
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.13/gopose_0.0.13_darwin_amd64.tar.gz"
      sha256 "cc9752c11fe542b91e4586f87900baeb637491c69cf0ee3f129891acccfa604c"

      def install
        bin.install "gopose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.13/gopose_0.0.13_darwin_arm64.tar.gz"
      sha256 "14129104d60509c93d0691e254b00b192eeab0bada599644a98993ea044b87fa"

      def install
        bin.install "gopose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.13/gopose_0.0.13_linux_amd64.tar.gz"
      sha256 "2cd0188585ea8fc20519c730f7f052d7579ab15705fe69985fce7681b9df70fd"
      def install
        bin.install "gopose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.13/gopose_0.0.13_linux_arm64.tar.gz"
      sha256 "f9ba627508d6cafb57162b890c2b9983c2bdcc91ae902b3aa0160914fe921cc0"
      def install
        bin.install "gopose"
      end
    end
  end
end
