# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopose < Formula
  desc ""
  homepage ""
  version "0.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.15/gopose_0.0.15_darwin_amd64.tar.gz"
      sha256 "b2716d964c85e99bbd0c7d298d31bdd84255ef89d215bd222cfe81eaee77c46c"

      def install
        bin.install "gopose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.15/gopose_0.0.15_darwin_arm64.tar.gz"
      sha256 "a24ca1e8a93519f54784ce4011395ac605106502e1a2b7202541f294847a952d"

      def install
        bin.install "gopose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.15/gopose_0.0.15_linux_amd64.tar.gz"
      sha256 "a68671ec80cd83eb6ae46b94f2624928c90535ce1f43f5cf75cef33db06978f3"
      def install
        bin.install "gopose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harakeishi/gopose/releases/download/v0.0.15/gopose_0.0.15_linux_arm64.tar.gz"
      sha256 "93532b35a774befd6eb5776cd019547be6f09fbee1122f5bb7df5e8970824dab"
      def install
        bin.install "gopose"
      end
    end
  end
end
